---
- name: Install and config filebeat
  hosts: elastic-client
  remote_user: root
  vars:
    ansible_ssh_private_key_file: "{{elasticclientkey}}"
  # become: yes
  # become_method: sudo

  roles:
    - filebeat
