---
- name: Install and config elastic stack
  hosts: elastic-server
  remote_user: root
  vars:
    ansible_ssh_private_key_file: "{{elastickey}}"
  # become: yes
  # become_method: sudo

  roles:
    - elastic
