---
- name: ensure anonymous users are not in the database
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
    host_all: yes
  with_items:
    - 127.0.0.1
    - localhost
    - ::1

- name: Remove the test database
  mysql_db:
    name: test
    state: absent

- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host: "{{ item }}"
    password: 123456
    login_user: root
    login_password: 123456
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
